### ISSUE TITLE
implicit query parameter for security

### ISSUE THREAD

**Issue by dcharbonnier** [krakenjs/swaggerize-routes#81]
```
securityDefinitions:
  signature:
    type: apiKey
    name: sign
    in: query
/myroute/
  get:
    security:
      - signature: []
```
This should NOT be required :
```
  parameters:
      - name: sign
        in: query
        type: string
```
